[package]
name = "set_container_id"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
tokio = { version = "1.33", features = ["full"] }

zerocopy = "0.7"
futures = "0.3"

unreal = { path = "../unreal" }
